version: '3'
services:
  web:
    build:
      context: ./Front-End/login-signup
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment: # For hot reload
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes: # Proper mounting
      - ./Front-End/login-signup/src:/src/webapp/src
      - /Front-End/login-signup/node_modules/

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./backend:/src/backend

  database:
    image: postgres
    restart: always # Prevents stale state errors
    environment:
      POSTGRES_PASSWORD: cs222

  pgadmin:
    links:
      - database:database
    image: dpage/pgadmin4:3.0
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@dishdiaries.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "5050:80"
    restart: always

  proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"


