version: '3'
services:
  web:
    image: nginx
    ports:  
      - "3000:80"

  api:
    image: nginx
    ports:  
      - "443:80"

  proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
