version: '3'
services:
<<<<<<< HEAD

  web: # This will be eventually replaced with "web" below, this is just for testing purposes.
    image: nginx:1-alpine
    ports:
      - 3000:80

  # web:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "3000:3000"

  api: # This will be eventually replaced with "api" below, this is just for testing purposes.
    image: nginx:1-alpine
    ports:
      - 443:80

  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "443:443"
=======
  web:
    image: nginx
    ports:  
      - "3000:80"

  api:
    image: nginx
    ports:  
      - "443:80"
>>>>>>> e64ba1e9395b774287048a2029000c6e8fd74048

  proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
<<<<<<< HEAD
      - "80:80"
=======
      - "80:80"
>>>>>>> e64ba1e9395b774287048a2029000c6e8fd74048
